language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - lts/*
  - node
script:
  - npm test
jobs:
  include:
    - stage: coverage
      node_js: lts/*
      script: jest --coverage --coverageReporters=text-lcov | coveralls
    - stage: deploy
      node_js: lts/*
      script: skip
      deploy:
        provider: npm
        email: litichevskiydv@gmail.com
        api_key:
          secure: cSK5l1AAxex0JYmQhIrSr3rbjH1FdNPhm4JprDpXtG65uvaPSQ+MhzUAWNYKJsG0aRDJy7pJQRX97aljOxNXJNEKqgLqtUP+G1XxFV9WS2KD5KULUMk1ntnVT0nshc/DxKB8uFi0ytdnOClxxWNP+583o4lGCdbb4DSBL9JasCpaOrRglezo9p3d4vudn8ZDEm/PnsPXqNW1opcZRWzcetQEbtRWc/U97aNnssWXs4Zy1FsPBog+L6A/cFVofInd3OymasRhorzHMFOJnXMUnmXTD3Mpu14MaxBVSRzORV6f7dfHINfIovDX8AYMDvP+WomkxBLo80hdOItPYsRBo63BIAQPDDHZKM5g8Vo4vOC176YHVzyvm1JvHSExl/fnlXhxXvlGwtoqkprRjcBE7iO2rU8rWe/SWG+ET0YY/ZRk3XZC0TQmCV7NERyISUSl2J4SgQmCj/U7CgQckbkEX+DJ13dbHy6TpIDz0c2vAk7u4U8bkNjkEUJ1/u05zvLodSo4btDkwUO174sJ1IBXCXqzwfqg/LqCmoDpUvhTjiu9lseXBdnc565Ikffje9UWKmTiRJIG9TTnJ5mlnryQhxURaPrZWDB18OKuxdYi+o7Dg6HlGHA327tomRhqVI8LNaLbsrfIT9vUJ3keRPW7uzSS+Hrdk4SXyMn/jvYFqRw=
        on:
          branch: master
